# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: MY-USER
  CLOUD_SQL_PASSWORD: MY-PASSWORD
  CLOUD_SQL_DATABASE_NAME: MY-DATABASE-NAME
  CLOUD_SQL_CONNECTION_NAME: MY-CONNECTION-NAME
# [END gae_python37_cloudsql_config]
